### ISSUE TITLE
Add executor: `cmd`

### ISSUE THREAD

**Issue by spyzhov** [spyzhov/healthy#10]
```yaml
args:
    command: ["curl", "http://google.com"]
    required:
        code: Numeric
        content: Content
```
