### ISSUE TITLE
Add variables

### ISSUE THREAD

**Issue by spyzhov** [spyzhov/healthy#3]
Add support of variables, like:
```yaml
version: 1
name: example
groups:
  - name: DB
    variables:
      - name: GROUP_LEVEL
        value: example
    validate:  
      - name: "stable connection"
        type: SQL
        variables:
        - name: PASSWORD
          value: $PASSWORD
          masked: true
        - name: HOST
          value: localhost
        args:
          - url: 'postgresql://$PG_LOGIN:$PASSWORD@$HOST/dbname'
```
Where:
 - `$PG_LOGIN` - from global `env`
 - `$PASSWORD` - from global `env` should proceed to local and be masked for output
 - `$HOST` - a local variable with the scope of step given as a string
 - `$GROUP_LEVEL` - a local variable with the scope of the group
